services:
  - type: web
    name: don-bosco-connect-api
    env: python
    runtime: python3.12

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: MYSQL_HOST
        value: mysql-16529156-uped-419c.e.aivencloud.com

      - key: MYSQL_PORT
        value: "14086"

      - key: MYSQL_USER
        value: avnadmin

      - key: MYSQL_DB
        value: don_bosco_connect

      - key: SECRET_KEY
        value: AVNS_gbkKmZWVZapTrEspfyM
